### ISSUE TITLE
task_boards

### ISSUE THREAD

**Issue by ccstudiio** [Edmar-Sousa/kanban#1]
Illuminate\Database\QueryException

  SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'task_boards' (SQL: alter table `tasks` add constraint `tasks_taskboard_id_foreign` foreign key (`taskboard_id`) references `task_boards` (`id`) on delete cascade)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +9 vendor frames
  10  database/migrations/2023_04_05_210025_create_tasks_table.php:21
      Illuminate\Support\Facades\Facade::__callStatic()

      +22 vendor frames
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by Edmar-Sousa** [comment]
Obrigado por reportar o bug! Já foi corrigido.

**Comment by Edmar-Sousa** [comment]
Obrigado por reportar o bug! Já foi corrigido.
