### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by WesllemJose** [Edmar-Sousa/kanban#2]
Não sei se é uma dica válida para inserir no 'README.md', mas vale lembrar a galera que tá iniciando agora no Laravel que devemos gerar a app_key do projeto. 

Para fazer isso basta inserir no console 'php artisan key:generate' e a app_key será inserida no '.env'  após realizar a conexão com o database.

**Comment by Edmar-Sousa** [comment]
obrigado! README.md atualizado

**Comment by Edmar-Sousa** [comment]
obrigado! README.md atualizado
